### PR TITLE
Fixed a possible cause of position desync and vehicle instabilities

### PR DESCRIPTION
**Pull request by stefan750**
- Fixed incorrect center of gravity calculation on some cars where beams of detached parts do not break properly (thanks @Olrosse for catching this!)
- Limited the force applied to vehicles for correcting position and rotation to reduce vehicle instabilities

Tested by watching other people on public servers drive around for a while, and it does not cause any obvious issues and seems to help reduce instabilities by quite a bit.

### CODE REVIEW

**Comment by Starystars67** [comment]
Nice work @stefan750 , Are you ready for me to approve and merge this or are you still playing with it?

**Review by Starystars67 — APPROVED** [review]

**Review by Olrosse — APPROVED** [review]
The only instability i got when testing was when i used sun gravity, but that one was likely not relatied to velocity or MP, so id say its a significant improvement :) and testing included throwing several cars down crash hard including the lambo, sbr4, wigeon, belaz with thrusters etc, and i also found no issues during my testing

**Comment by Starystars67** [comment]
So that is a yes, you are ready to merge then?

**Comment by Olrosse** [comment]
> 
> 
> So that is a yes, you are ready to merge then?

well im not stefan xD but i would think since its been pull requested that it is ready?

**Comment by Starystars67** [comment]
I'm happy to go with that haha!

**Pull request merged**
