### PR TITLE
Transbreak / LineLock additions (meöw)

### PR DESCRIPTION
**Pull request by 20dka**

### CODE REVIEW

**Comment by jojos38** [comment]
Looks good although the whole if else logic can be simplified to
```
if decodedData.transbrake ~= nil then
  if electrics.values.transbrake ~= decodedData.transbrake then
	  controller.getController("transbrake").setLineLock(decodedData.transbrake)
  end
end

if decodedData.lineLock ~= nil then
  if electrics.values.lineLock ~= decodedData.linelock then
	  controller.getController("lineLock").setLineLock(decodedData.linelock)
  end
end
```
Would be perfect if after you change it

**Review by Starystars67 — CHANGES_REQUESTED** [review]
Looks good. Just the 2 edits as suggested by @jojos38 and we are good for a merge!
Nice work @20dka !

**Review by Starystars67 — APPROVED** [review]

**Review by jojos38 — APPROVED** [review]
All good

**Comment by 20dka** [comment]
sick

**Pull request merged**
