### PR TITLE
Updated credits.html to the 0.23 changes

### PR DESCRIPTION
**Pull request by Olrosse**

### CODE REVIEW

**Comment by Olrosse** [comment]
hmm, any idea why it shows/added the old commits that i though are the same as current dev build?

**Comment by 20dka** [comment]
Because you forgot to rebase before starting your new work your fork doesn't know that those already exist on remote

**Comment by lionkor** [comment]
Maybe the branch you were working from wasn't up to date? You can do a git rebase onto BeamMP:development, it should come with few (if any) merge issues.

Should merge fine though either way.

**Comment by Olrosse** [comment]
i clicked the fetch upstream and merge before working on it, is there a different button i've missed? i also see now that it only says one file changed so yeah im guessing it should merge fine anyways

**Review by Starystars67 — APPROVED** [review]

**Review by 20dka — APPROVED** [review]

**Comment by lionkor** [comment]
What happened here? Why was this closed?

**Comment by Olrosse** [comment]
> What happened here? Why was this closed?

Gonna re PR since i was told there was conflicts, just gotta figure out how to rebase properly, so far i have only found the fetch upstream and merge button, but it still says I'm 5 commits ahead for whatever reasons

**Comment by lionkor** [comment]
The GUI will not help you much there, I think. I would recommend GitExtensions, but that has to be taught, etc. 

Either way the command you want is something like

```sh
git remote add upstream https://github.com/BeamMP/BeamMP
git rebase upstream/development
git push -u origin development -f
```

DM me on discord if you need help.

**Comment by Olrosse** [comment]
> The GitHub GUI will not help you much there, I think. I would recommend GitExtensions, but that has to be taught, etc.
> 
> Either way the command you want is something like
> 
> ```shell
> git remote add upstream https://github.com/BeamMP/BeamMP
> git rebase upstream/development
> git push -u origin development -f
> ```
> 
> DM me on discord if you need help.

Thanks :) I'll let you know if i have any trouble with it

**Pull request closed without merging**
