### PR TITLE
Reworked how inputs are synced to avoid "Ghost Controlling"

### PR DESCRIPTION
**Pull request by prestonelam2003**
Inputs are now directly synced, this will keep "Ghost Controlling" from being a problem, the steering wheel is smoothed to make watching other player bearable. I think this A: looks much better and B: allows for people to tab onto other's cars without an immersion break.

### CODE REVIEW

**Comment by jojos38** [comment]
This looks quite good, there is just one thing that I don't understand if you have 5 minutes you can dm me on Discord if we can take a look at it (about the workaround for mpVehicleType)

Also if you could just update the variable update with this:
`
--
-- update lastApply with currentApply before it's updated
lastApply = {
	s = currentApply.s or decodedData.s,
	t = currentApply.t or decodedData.t,
	b = currentApply.b or decodedData.b,
	p = currentApply.p or decodedData.p,
	c = currentApply.c or decodedData.c
}

--update currentApply
currentApply = {
	s = decodedData.s,
	t = decodedData.t,
	b = decodedData.b,
	p = decodedData.p,
	c = decodedData.c
}
`

Overwise it looks pretty cool well done!

**Comment by Starystars67** [comment]
When this is ready it needs to be merged into development rather than master please!

**Review by Starystars67 — COMMENTED** [review]
Looks good!

**Comment by Starystars67** [comment]
Sorry for that but all work is put into the dev branch first.

**Comment by jojos38** [comment]
There is still some stuff to fix, it's mostly good

**Comment by Starystars67** [comment]
@prestonelam2003 could we address this ready to merge?

**Review by jojos38 — APPROVED** [review]
Still need changes but nothing major for now

**Comment by Starystars67** [comment]
> Still need changes but nothing major for now

@jojos38 what changes? 
As I will not approve until we know it is good. If it needs changes then it is not in a state ready for merge.

**Comment by jojos38** [comment]
> > Still need changes but nothing major for now
> 
> @jojos38 what changes? 
> As I will not approve until we know it is good. If it needs changes then it is not in a state ready for merge.

The mpVehicleType variable is defined in two different parts of the code therefor having code duplication and wasted cpu. It doesn't break the mod tho

**Comment by Starystars67** [comment]
@prestonelam2003 can you look into this, then we can merge it.

**Review by Starystars67 — APPROVED** [review]
There we go, thank you.

**Comment by Starystars67** [comment]
@jojos38 @prestonelam2003 @20dka  can we get a go, no go on this please.

**Comment by 20dka** [comment]
I'd like my changes that touch this part of the codebase to be merged first, as they could change/simplify Preston's code, and I don't want my changes to override his and cause merge issues

**Comment by Starystars67** [comment]
So this can be done now then?

**Comment by prestonelam2003** [comment]
Just a quick reminder, this pull request is to fix the glitchy "ghost controlling" you can do to other player's cars, it helps keep immersion and lessens load on support (Though it's not as common now, I have heard people say numerous times "I can control this guy's car, bro we're fighting over the wheel")
Lastly, this rework of how inputs are handled makes inputs more reflective of their true values.

Rebased to resolve conflicts
Removed workaround for `v.mpVehicleType`
Resolved problem where wheel would freeze in place when moving quickly
Added damping as steering gets closer to it's "target" which in simple terms makes the wheel much smoother.

Still may need a tad more work, but I believe it should be in a state suitable for the development build.

**Review by Starystars67 — COMMENTED** [review]
Nice

**Comment by Starystars67** [comment]
Looks good to me, Im okay with merging here! @jojos38 if you have no issues and also @20dka i know you did have a concern with one of the PR's so if your good with it lets get this merged into this please!

**Comment by 20dka** [comment]
it has been updated and my concerns have been addressed, i will pull and try it tonight then we can merge

**Comment by Starystars67** [comment]
Thank you @20dka , Please report back as soon as you have an answer so we can merge!

**Comment by Starystars67** [comment]
@20dka any update?

**Pull request merged**
