### PR TITLE
Further rewrite to the UI

### PR DESCRIPTION
**Pull request by jojos38**
- Rewrote the multiplayer.js further, a last pass is still needed to clean up last stuff
- Added ability to sort servers by clicking on table headers, refresh to reset
- Rewrote favorites and recents servers to be simpler and more optimized
- Added some pretty fades and animations
- Performances improvement (to the UI)

https://www.youtube.com/watch?v=1lu492Ava94

**Known issues: **
- Recent servers are sorted wrong way (most recent are at the bottom)
- If you sort using the table header after clicking on a the server, the server menu stays open (should be easy to fix, I'll fix it asap)

### CODE REVIEW

**Review by Starystars67 — COMMENTED** [review]
Looks good to me, couple of small things but nothing major to comment on. Nice work!

**Comment by Starystars67** [comment]
I have now changed this to merge to development as it should be. Please can you review the conflicts and what not @jojos38 . 
We cannot merge until this is done and we have a go ahead from deerboi too at minimum since it has work by him in this branch recently. Might be worth getting @stefan750 too though most of his work sits within Lua only..

**Comment by Starystars67** [comment]
Oh plus your Known issues. lets get them resolved too before merging. Sorry.

**Comment by Starystars67** [comment]
I see you merged it, did you address the conflicts and get deerbois input?

**Comment by jojos38** [comment]
> I see you merged it, did you address the conflicts and get deerbois input?
Deer boi told me it's ok on Discord, I should have fixed the conflicts yeah

**Comment by Starystars67** [comment]
Okay thank you. I just want to make sure we are working as a team and ensuring that the workflow reflects that too.
Remember the work in this branch stays here until we have all tested it. From there it can be moved to the earlyaccess branch when the new launcher and server are ready too. Then we can actually have EA test it once again.

**Pull request merged**
