### PR TITLE
bugfixes

### PR DESCRIPTION
**Pull request by 20dka**
it works ayy

(except for snowmen not dissapearing on 0.22.2 but thats not our fault)

### CODE REVIEW

**Comment by Starystars67** [comment]
Does this contain the fix for the MPVehicleGE issues found recently?

**Review by Starystars67 — APPROVED** [review]
Looks like it would solve some of the issues.

**Comment by 20dka** [comment]
not sure which issue you found as there were a few, but yes i fixed everything i found and used this build yesterday (batman and olrosse tested it too)

**Comment by Starystars67** [comment]
The issues yesterday were 1 the camera was stuck in freecam & vehicles start glitching like duplicating and flying around :P

**Review by Anonymous-275 — APPROVED** [review]

**Pull request merged**
