### PR TITLE
README Rewrite

### PR DESCRIPTION
**Pull request by lionkor**
Hey guys, 

I noticed the README was **super** out of date. I rewrote almost the entirety of it, mostly linking instead of copy-pasting the guide(s).

### CODE REVIEW

**Comment by lionkor** [comment]
Look at [this](https://github.com/BeamMP/BeamMP/tree/3d6086a7533e7fe47829a9f702acd35bb153753c) for a nice preview

**Comment by Starystars67** [comment]
Well hot damn!
Looking pretty fine! One suggestion that might be worth having would be maybe have a section about the past of the project?
Just an idea that's all. Otherwise I am goo with a merge so I will approve now either way.

**Review by Starystars67 — APPROVED** [review]

**Comment by lionkor** [comment]
Glad you like it! The past of the project sounds like a fun thing to write out, a short little history - but I'm likely the wrong person to write that. I think it should be a separate page on the website, maybe?

**Comment by Starystars67** [comment]
Fair enough there. Do you think we should mention anything about network codes or leave that out / something for the wiki?

**Comment by lionkor** [comment]
The network codes are quite arbitrary and the data format is also important, so we're better off writing a full guide on the wiki.
I'm all for Readme's that link instead of being *the* place to get any info you can't get anywhere else :D

**Pull request merged**
