### PR TITLE
crash, glitch, bugfixes, walking mode improvements

### PR DESCRIPTION
**Pull request by 20dka**
exit cars on the right side
universal passenger camera

cant enter another snowman (dupe glitch fix)

setting to specify launcher ip (useful when loopback address fails)

working color sync on veh update, electrics blacklist expanded
regexp matches and network bugfix
support for part prices in the UI

reworked vehicle switch logic (crash fix)

### CODE REVIEW

**Review by jojos38 — APPROVED** [review]
This is super cool, well done

**Review by Starystars67 — COMMENTED** [review]
Does this contain history or is it just the very last message?

**Comment by 20dka** [comment]
just the very last, we can implement full history later, but this is already very helpful for repetitive commands (/countdown, /mission)

**Comment by Starystars67** [comment]
> just the very last, we can implement full history later, but this is already very helpful for repetitive commands (/countdown, /mission)

Agreed! Please could you add to the trello or as an issue to improve this to a full history rather than last message only.

Other than that. Happy to approve and merge if you are ready?

**Comment by 20dka** [comment]
yeah i will. im working on rewriting our prints to logs instead as per your first comment, id wait until that's done (hopefully today)

**Comment by Starystars67** [comment]
Okay. Let me know when you're ready. Otherwise nice work!

**Review by Starystars67 — APPROVED** [review]

**Pull request merged**
