### PR TITLE
Fixes and improvements

### PR DESCRIPTION
**Pull request by jojos38**
**MERGE THE #95 COMMIT BEFORE THIS ONE**

- Fixed servers not showing when favorites.json is missing
- Improved map loading logic
- If the map is missing from the game a message is shown to the user
- Slightly improved the UI

Thanks to @20dka for the help

### CODE REVIEW

**Review by 20dka — APPROVED** [review]
mhm yes good

**Comment by Starystars67** [comment]
Are we good here now then?

**Review by Starystars67 — APPROVED** [review]

**Review by jojos38 — COMMENTED** [review]
Gud

**Comment by Anonymous-275** [comment]
looks good

**Review by Anonymous-275 — APPROVED** [review]

**Pull request merged**
